### ISSUE TITLE
Misleading file extensions?

### ISSUE THREAD

**Issue by Sslaxx** [ben-rolfe/icbm#2]
I've noticed that in the `story/start` directory (and, I'd imagine, other folder(s) as and when they get added) there is a `_.txt` file - except that it isn't text, which causes some confusion if you try to open it up in a text editor. I'd imagine giving it a more meaningful extension - maybe `.page`? - might help.

**Comment by ben-rolfe** [comment]
Good point! They were text files originally, and part of me still thinks they should be. I'll have a think, but either way, as you say, the extension shouldn't be txt if they're not.

**Comment by ben-rolfe** [comment]
Story files now use the `.dat` extension instead of `.txt`
(Since this is not a recognised text file format, the files don't appear in the godot editor, but that's probably a good thing, since they can't be edited in the editor, anyway)
